In [ ]:
import numpy as np
array1d = np.array([11, 24, 37])
print(array1d)

array2d = np.array([[1, 2], [3, 4]])
print(array2d)

zeros_array = np.zeros((2, 3))
print(zeros_array)

array = np.array([1, 2, 3], dtype='float32')
print(array)

[11 24 37]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 2. 3.]


In [ ]:
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))
print(np.hstack((a, b)))
array = np.arange(6).reshape(2, 3)
print(np.hsplit(array, 3))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]


In [ ]:
import numpy as np
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
new_array = array + 10
print(new_array)

[11 12 13 14 15]


In [ ]:
import numpy as np
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
column_sum = np.sum(array_2d, axis=0)
print(column_sum)

[ 9 12]
